### ISSUE TITLE
 module(tesmart-hdmimatrix): Module identifies itself as tesmart-hdmi-matrix and has been disabled.

### ISSUE THREAD

**Issue by cprima** [bitfocus/companion-module-tesmart-hdmimatrix#2]
It seems that the module is not activated, at least from what I gather in the logs:

My Installation:
Rapsberry Pi / "Beta"
git pull says "Already up to date".

When restarting Companion I get the log mesage
>21.11.17 09:39:14 module(tesmart-hdmimatrix): Module identifies itself as tesmart-hdmi-matrix and has been disabled.

**Comment by estilles** [comment]
Thanks for reporting @cprima! Again! :-)
