### ISSUE TITLE
Unable to make this work from Mac/Chrome

### ISSUE THREAD

**Issue by AnthonyHunt** [bitfocus/companion-module-tesmart-hdmimatrix#4]
Finally got to implement this in the live environment. The module connects and gives no errors. When I send a button command nothing happens.

If I add a TCP-UDP connection and connect I can manually send a command like MT00SW0202NT with /r/n but the module doesn't seem to send the commands properly? Any thought? I will try the debug session from my dev machine when I'm next on site. 

My thoughts so far is that the variable is getting mashed in the string build? or the send?

**Comment by dhf** [comment]
Same here on Mac OS. There is also no message in the log (also not in the debug section of the log).

**Comment by josephdadams** [comment]
@jrvviz can you look at this?

**Comment by jrviz** [comment]
The current code is creating and destroying the socket for every command . There is a timing and scope hazard here I think as the asynchronous function may not have access to the command variable

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by josephdadams** [comment]
So this should be fixed in #5

**Comment by jrviz** [comment]
There are a number of new config option in this release so if you have this module loaded you should open config, set up your configuration and save.
